server:
  port: 8081

spring:
  application:
    name: market-monitoring-agent

market:
  binance:
    stream-url: wss://stream.binance.com:9443/ws/btcusdt@kline_1s
    symbol: BTCUSDT

python:
  agent:
    base-url: ${PYTHON_AGENT_BASE_URL:http://localhost:8000}


trading:
  initial-balance: 10000.0