name: build-and-push-java

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: registry.digitalocean.com

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login to DO Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build and push
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ secrets.DO_REGISTRY }}/java-market:${GITHUB_SHA}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
